# Generated by Django 4.2.1 on 2023-05-22 16:32

from django.db import migrations, models
import users.models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_name_middle_user_reference_user_time_deleted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="last_login",
        ),
        migrations.AlterField(
            model_name="user",
            name="name_first",
            field=models.CharField(
                max_length=128, null=True, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="reference",
            field=models.CharField(
                default=users.models.generate_reference,
                max_length=128,
                unique=True,
                verbose_name="reference",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="title",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                null=True,
                unique=True,
                verbose_name="uuid",
            ),
        ),
    ]
